<h1> Genel Durum</h1>
<hr />
<table class="table table-hover">
      <thead>
        <tr>
          <th>Adı</th>
          <th>Güç</th>
          <th>P</th>
          <th>O</th>
          <th>G</th>
          <th>B</th>
          <th>M</th>
          <th>Av.</th>
        </tr>
      </thead>
      <tbody>
          
<!-- Genel Durum -->
<?php 
if(count($this->teams)){
    $gamesModel = new Application_Model_DbTable_Games();
    foreach ($this->teams as $team) { 
        $team_info = $gamesModel->getTeamStatus($team->id);
?>
          
          <tr>
            <td><?php echo $team->name; ?></td>
            <td><?php echo $team->strength; ?></td>
            <td><?php echo $team_info['point'] ?></td>
            <td><?php echo $team_info['played_games_number'] ?></td>
            <td><?php echo $team_info['win'] ?></td>
            <td><?php echo $team_info['draw'] ?></td>
            <td><?php echo $team_info['defeat'] ?></td>
            <td><?php echo $team_info['avarage'] ?></td>
          </tr>
<?php
    }
}
?>
      </tbody>
    </table>
<!-- Genel Durum Bitisi -->


<hr /><br />
<h3>Haftalara Göre Durumlar</h3>
<?php
//eslestirme yapilmis mi
if($this->matches_status){
    $teamModel = new Application_Model_DbTable_Teams();
    foreach ($this->matches as $week) {  
        echo "<h1>". $week['week'].". Hafta</h1>";
?>
        <!-- haftalik puan durumu -->
        <table class="table table-hover">
              <thead>
                <tr>
                  <th>Adı</th>
                  <th>Güç</th>
                  <th>P</th>
                  <th>O</th>
                  <th>G</th>
                  <th>B</th>
                  <th>M</th>
                  <th>Av.</th>
                </tr>
              </thead>
              <tbody>
        <?php 
        if(count($this->teams)){
            $gamesModel = new Application_Model_DbTable_Games();
            foreach ($this->teams as $team) { 
                $team_info = $gamesModel->getTeamStatus($team->id,$week['week']);
        ?>

                <tr>
                  <td><?php echo $team->name; ?></td>
                  <td><?php echo $team->strength; ?></td>
                  <td><?php echo $team_info['point'] ?></td>
                  <td><?php echo $team_info['played_games_number'] ?></td>
                  <td><?php echo $team_info['win'] ?></td>
                  <td><?php echo $team_info['draw'] ?></td>
                  <td><?php echo $team_info['defeat'] ?></td>
                  <td><?php echo $team_info['avarage'] ?></td>
                </tr>
        <?php
            }
        }
        ?>
            </tbody>
        </table>
        <!-- Haftalik puan durumu bitisi -->




        <!-- haftanin maclari -->
        <table class="table table-hover">
              <thead>
                <tr>
                  <th>Ev Sahibi Takım</th>
                  <th>Konuk Takım</th>
                  <th>Skor</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>

        <?php
                foreach ($week['matches'] as $match) {
                    echo "<tr>";
                    $firstTeam = $teamModel->getByFilter(array('id' => $match->first_team_id));
                    $secondTeam = $teamModel->getByFilter(array('id' => $match->second_team_id));
                    echo "<td>".$firstTeam->name."</td>";
                    echo "<td>".$secondTeam->name."</td>";
                    if($week['games_played_status']){
                        echo "<td>".$match->first_team_goal."-". $match->second_team_goal."</td>";
                        echo "<td><a href='".$this->baseUrl('/backend/score-edit/'.$match['id'])."' class='btn btn-warning btn-sm'>Skoru Duzenle</a></td>";
                    }
                    else{
                        echo "<td>Oynanmadi</td>";
                    }
                    
                  }
                  echo "</tbody>
                  </table>";
                  if(!$week['games_played_status']){
                        echo "<a href='".$this->baseUrl('/backend/play-games/').$week['week']."' class='btn btn-primary'>Maçları Oynat</a>";
                  }
                  echo "<br><br>";
            }
}


else{
    echo "<strong> Henuz eşleştirme yapılmadı... </strong> <br/>";
    echo "<a class='btn btn-primary' href='".$this->baseUrl('/backend/match')."'>Eslestir</a>";
}
?>
<hr>
<center>
  
   <?php
   //Eger eslestirme yapildiysa tum maclari oynat butonu gelsin
    if($this->matches_status){ ?>    
        <a href="<?php echo $this->baseUrl('/backend/play-all-weeks')?>" class="btn btn-lg btn-warning">Bütün Maçları Oynat</a>
   <?php } ?>
    <br><br>
    <a href="<?php echo $this->baseUrl('/backend/reset-matches')?>" class="btn btn-lg btn-danger">Maçları Sıfırla</a>
</center>