<h1> Takımlar </h1>
<hr />
<table class="table table-hover">
      <thead>
        <tr>
          <th>Adı</th>
          <th>Başarı Oranı</th>
          <th>**</th>
          <th>**</th>
        </tr>
      </thead>
      <tbody>
<?php 
if(count($this->teams)){
    foreach ($this->teams as $team) { ?>
          <tr>
            <td><?php echo $team->name; ?></td>
            <td><?php echo $team->strength; ?></td>
            <td><a href="<?php echo $this->baseUrl()."/backend/edit-team/".$team->id; ?>" class="btn btn-warning">Düzenle</a></td>
            <td><a href="<?php echo $this->baseUrl()."/backend/delete-team/".$team->id; ?>" class="btn btn-danger">Sil</a></td>
          </tr>
<?php
    }
}
?>
      </tbody>
    </table>
<hr /><br />

<?php if(isset($this->form)){
    echo "<h4>Yeni Takım Ekle</h4>";
    echo $this->form;    
}