<!DOCTYPE html>
<html>
    <head>
        <link href="/default/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/default/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/default/css/bootstrap-theme.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/default/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css" >
        <style type="text/css">
	  body {
		padding-bottom: 40px;
	  }
	  .sidebar-nav {
		padding: 9px 0;
	  }
          .errors li {
            color:red;
            }
	</style>
	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- The fav icon -->
	<link rel="shortcut icon" href="<?php echo $this->baseUrl().'/adminpages/img/favicon.ico'?>">

    </head>

    <body>
        <div class="container" style="margin-top:14%">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading"><h3 class="panel-title"><strong>Sign in </strong></h3></div>
                    <div class="panel-body">
                        <form action="login" method="post">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Username or Email</label>
                                <input type="email" name="email" class="form-control" style="border-radius:0px" id="exampleInputEmail1" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                 <label for="exampleInputPassword1">Password</label>
                                 <input type="password" name="password" class="form-control" style="border-radius:0px" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-sm btn-default">Sign in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
