<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li class="active"><a href="<?php echo $this->baseUrl("/backend"); ?>"><i class="fa fa-dashboard"></i> Takımlar</a></li>
           <li class="active"><a href="<?php echo $this->baseUrl("/backend/games"); ?>"><i class="fa fa-dashboard"></i> Maçlar</a></li>
            <li><a href="<?php echo $this->baseUrl("/backend/logout"); ?>"><i class="fa fa-file"></i> <strong>Cikis Yap</strong></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
     