<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <title>Deneme Admin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <?php echo $this->render('_header.phtml').PHP_EOL; ?>  
</head>
<body>
    <div id="wrapper">

    <?php echo $this->render('_navbar.phtml').PHP_EOL; ?>
      

      <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <?php echo $this->render('_displayMessages.phtml').PHP_EOL; ?>
            <?php echo $this->layout()->content; ?>
          </div>
        </div><!-- /.row -->

      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

</body>
</html>