<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
              <li class="active"><a href="<?php echo $this->baseUrl("/"); ?>"><i class="fa fa-dashboard"></i> <strong>Anasayfa</strong></a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/1"); ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate('1.Hafta');?></a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/2"); ?>"><i class="fa fa-dashboard"></i> 2.Hafta</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/3"); ?>"><i class="fa fa-dashboard"></i> 3.Hafta</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/4"); ?>"><i class="fa fa-dashboard"></i> 4.Hafta</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/5"); ?>"><i class="fa fa-dashboard"></i> 5.Hafta</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/fixture-of-week/6"); ?>"><i class="fa fa-dashboard"></i> 6.Hafta</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/all-weeks"); ?>"><i class="fa fa-dashboard"></i> Tüm Haftalar</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl("/index/login"); ?>"><i class="fa fa-dashboard"></i> Admin Login</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
     